@FixFlow.API_HostAddress = http://localhost:5130

POST {{FixFlow.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "companyName": "Vektor Mantenimiento Industrial",
  "companyRut": "76.123.456-K",
  "services": "Mantenimiento Industrial",
  "fullName": "Pablo Órdenes",
  "email": "pablo.admin@vektor.cl",
  "password": "PasswordSegura2026!",
  "userRut": "19.876.543-2"
}

###
